export function renderHtml() {
  return `<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Assistente de Triagem de Cobranças</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172019;background:#f5f7f5;line-height:1.5}*{box-sizing:border-box}body{margin:0}header{background:#173f2a;color:white;padding:28px 20px}header .wrap,main{max-width:1080px;margin:auto}.eyebrow{font-size:12px;letter-spacing:.08em;text-transform:uppercase;opacity:.8}.hero{display:grid;gap:10px}h1{font-size:clamp(28px,5vw,44px);margin:0}header p{max-width:760px;margin:0;color:#dce8df}main{padding:26px 20px 60px;display:grid;gap:20px}.panel{background:white;border:1px solid #dde5df;border-radius:16px;padding:20px;box-shadow:0 8px 24px rgba(19,50,31,.05)}.limits{display:grid;gap:8px}.limits li{margin:4px 0}.warning{border-left:4px solid #bd8b1f;background:#fff9e9;padding:12px 14px;border-radius:8px}label{display:block;font-weight:700;margin-bottom:8px}textarea,input{width:100%;border:1px solid #cbd7ce;border-radius:10px;padding:12px;font:inherit;background:white}textarea{min-height:220px;resize:vertical}.actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:12px}button{border:0;border-radius:10px;padding:11px 16px;font-weight:700;cursor:pointer}.primary{background:#306927;color:white}.secondary{background:#e8efe9;color:#21472e}.ghost{background:transparent;border:1px solid #ccd7cf}.status{margin-top:12px;min-height:24px}.error{color:#9e271f}.success{color:#27623a}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.card{border:1px solid #e0e7e2;border-radius:12px;padding:14px;background:#fbfcfb}.card h3{font-size:14px;margin:0 0 8px;color:#34533e}.badge{display:inline-flex;padding:5px 9px;border-radius:999px;background:#e8efe9;font-weight:800}.tool{border-color:#a9c9b3;background:#f2faf4}.hidden{display:none!important}.history-item{width:100%;text-align:left;background:#f7faf7;border:1px solid #e3eae5;margin:6px 0}.muted{color:#647269;font-size:14px}ul.clean{padding-left:20px;margin:8px 0}.result-head{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}@media(max-width:650px){header{padding-top:20px}.panel{padding:15px}}
</style>
</head>
<body>
<header><div class="wrap hero"><div class="eyebrow">Workflow inteligente — Semana 4</div><h1>Assistente de Triagem de Cobranças</h1><p>Analise cobranças recebidas por e-mail, organize informações importantes e identifique o que exige atenção. A decisão final continua sendo humana.</p></div></header>
<main>
<section class="panel limits"><h2>O que este assistente NÃO faz</h2><ul><li>Não confirma que boleto, Pix ou cobrança é legítimo.</li><li>Não autoriza pagamentos nem toma decisão de crédito.</li><li>Não substitui compliance, análise fiscal ou validação bancária.</li><li>Não inventa informações ausentes.</li></ul><div class="warning">Não envie senhas, dados bancários completos, documentos pessoais sensíveis ou informações sigilosas.</div></section>
<section class="panel"><label for="conteudo">Conteúdo do e-mail</label><textarea id="conteudo" placeholder="Cole aqui o texto da cobrança recebida..."></textarea><div class="actions"><button id="exemplo" class="secondary">Carregar exemplo</button><button id="analisar" class="primary">Analisar cobrança</button></div><div id="status" class="status" aria-live="polite"></div></section>
<section id="resultado" class="panel hidden"><div class="result-head"><h2>Resultado da análise</h2><span id="badge" class="badge"></span></div><div id="avisoTool" class="warning hidden"></div><div id="dadosConsultados" class="card tool hidden"></div><div id="foraEscopo" class="card hidden"></div><div id="cards" class="grid"></div><div id="acompanhamentoBox" class="hidden" style="margin-top:18px"><label for="acompanhamento">Pergunta de acompanhamento</label><input id="acompanhamento" placeholder="Ex.: e se o vencimento fosse amanhã?"/><div class="actions"><button id="enviarAcompanhamento" class="secondary">Reavaliar</button><button id="nova" class="ghost">Nova análise</button></div></div></section>
<section class="panel"><h2>Histórico da sessão</h2><p class="muted">Mantido apenas nesta sessão do navegador.</p><div id="historico"></div></section>
</main>
<script>
const els = Object.fromEntries(['conteudo','exemplo','analisar','status','resultado','badge','avisoTool','dadosConsultados','foraEscopo','cards','acompanhamentoBox','acompanhamento','enviarAcompanhamento','nova','historico'].map(id=>[id,document.getElementById(id)]));
const historyKey='triagem-cobrancas-history-v1';
const example='Olá,\\n\\nSegue cobrança referente ao fornecimento realizado neste mês.\\n\\nEmpresa: Empresa Exemplo Ltda.\\nCNPJ: 19.131.243/0001-97\\nValor: R$ 4.850,00\\nVencimento: 15/09/2026\\n\\nAtenciosamente,\\nFinanceiro';
function getHistory(){try{return JSON.parse(sessionStorage.getItem(historyKey)||'[]')}catch{return []}}
function setHistory(v){sessionStorage.setItem(historyKey,JSON.stringify(v.slice(-8)));renderHistory()}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function list(items){if(!Array.isArray(items)||!items.length)return '<span class="muted">Não informado</span>';return '<ul class="clean">'+items.map(x=>'<li>'+escapeHtml(x)+'</li>').join('')+'</ul>'}
function card(title,body){return '<article class="card"><h3>'+escapeHtml(title)+'</h3>'+body+'</article>'}
function renderResult(data){els.resultado.classList.remove('hidden');els.cards.innerHTML='';els.foraEscopo.classList.add('hidden');els.dadosConsultados.classList.add('hidden');els.avisoTool.classList.toggle('hidden',!data.aviso_tool);els.avisoTool.textContent=data.aviso_tool||'';
 if(data.dados_consultados){const d=data.dados_consultados;els.dadosConsultados.innerHTML='<h3>Dados consultados</h3><strong>Fonte:</strong> '+escapeHtml(d.fonte)+'<br><strong>Data:</strong> '+escapeHtml(d.data_consulta)+'<br><strong>CNPJ:</strong> '+escapeHtml(d.cnpj)+'<br><strong>Razão social:</strong> '+escapeHtml(d.razao_social||'Não informado')+'<br><strong>Situação cadastral:</strong> '+escapeHtml(d.descricao_situacao_cadastral||'Não informado')+'<br><strong>Município/UF:</strong> '+escapeHtml((d.municipio||'Não informado')+'/'+(d.uf||'Não informado'));els.dadosConsultados.classList.remove('hidden')}
 const a=data.analise||{};if(a.status_analise==='fora_do_escopo'){els.badge.textContent='Fora do escopo';els.foraEscopo.innerHTML='<h3>Fora do escopo</h3><p>Este sistema foi desenvolvido para triagem de cobranças e e-mails de fornecedores.</p>';els.foraEscopo.classList.remove('hidden');els.acompanhamentoBox.classList.add('hidden');return}
 els.badge.textContent=a.classificacao||'Revisão necessária';const d=a.dados_identificados||{};const v=a.verificacao_cadastral||{};
 els.cards.innerHTML=[card('Classificação','<strong>'+escapeHtml(a.classificacao||'Revisão necessária')+'</strong><p>'+escapeHtml(a.justificativa_classificacao||'Informações insuficientes para uma classificação confiável.')+'</p>'),card('Resumo da cobrança','<p>'+escapeHtml(a.resumo||'Não informado')+'</p>'),card('Dados identificados no e-mail','<strong>Empresa/remetente:</strong> '+escapeHtml(d.empresa_ou_remetente||'Não informado')+'<br><strong>Valor:</strong> '+escapeHtml(d.valor||'Não informado')+'<br><strong>Vencimento:</strong> '+escapeHtml(d.vencimento||'Não informado')+'<br><strong>CNPJ:</strong> '+escapeHtml(d.cnpj||'Não informado')),card('Verificação cadastral','<p>'+escapeHtml(v.mensagem||'Não realizada.')+'</p>'),card('Pontos de atenção',list(a.pontos_de_atencao)),card('Próximo passo recomendado',list(a.proximo_passo)+'<p><strong>Validação humana necessária.</strong></p>')].join('');els.acompanhamentoBox.classList.remove('hidden');}
async function callAnalyze(acompanhamento=''){const conteudo=els.conteudo.value.trim();if(!conteudo){els.status.textContent='Cole o conteúdo de uma cobrança para iniciar a análise.';els.status.className='status error';return}els.analisar.disabled=true;els.enviarAcompanhamento.disabled=true;els.status.textContent='Analisando cobrança...';els.status.className='status';try{const hist=getHistory().slice(-3).map(x=>({pergunta:x.pergunta||x.conteudo,resposta:x.resumo||''}));const res=await fetch('/api/analisar',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({conteudo,acompanhamento,historico:hist})});const data=await res.json();if(!res.ok)throw new Error(data.erro||'Não foi possível concluir a análise.');renderResult(data);els.status.textContent='Análise concluída.';els.status.className='status success';const h=getHistory();h.push({data:new Date().toLocaleString('pt-BR'),conteudo,pergunta:acompanhamento||conteudo,resumo:JSON.stringify(data.analise),classificacao:data.analise?.classificacao||data.analise?.status_analise});setHistory(h)}catch(e){els.status.textContent=e.message;els.status.className='status error'}finally{els.analisar.disabled=false;els.enviarAcompanhamento.disabled=false}}
function renderHistory(){const h=getHistory().slice().reverse();els.historico.innerHTML=h.length?h.map((x,i)=>'<button class="history-item" data-i="'+(h.length-1-i)+'"><strong>'+escapeHtml(x.classificacao||'Análise')+'</strong><br><span class="muted">'+escapeHtml(x.data)+' — '+escapeHtml((x.conteudo||'').slice(0,80))+'</span></button>').join(''):'<span class="muted">Nenhuma análise nesta sessão.</span>';els.historico.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{const x=getHistory()[Number(b.dataset.i)];els.conteudo.value=x.conteudo||'';window.scrollTo({top:0,behavior:'smooth'})}))}
els.exemplo.addEventListener('click',()=>{els.conteudo.value=example});els.analisar.addEventListener('click',()=>callAnalyze());els.enviarAcompanhamento.addEventListener('click',()=>{const q=els.acompanhamento.value.trim();if(q)callAnalyze(q)});els.nova.addEventListener('click',()=>{els.conteudo.value='';els.acompanhamento.value='';els.resultado.classList.add('hidden');els.status.textContent='';els.conteudo.focus()});renderHistory();
</script>
</body></html>`;
}
